# Generated by Django 5.0.4 on 2024-04-20 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='dream',
            name='recorded_at',
        ),
        migrations.AddField(
            model_name='dream',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
