# Generated by Django 5.0.4 on 2024-04-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_rename_description_dream_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='dream_voice/'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
