# Generated by Django 5.0.4 on 2024-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_dream_voice_recording_alter_dream_date_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='voice_recording',
        ),
        migrations.AlterField(
            model_name='dream',
            name='date_recorded',
            field=models.DateField(),
        ),
    ]
