# Generated by Django 5.0.4 on 2024-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_remove_dream_voice_recording_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='content',
            new_name='description',
        ),
    ]
